// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScheduledMeets.Persistence;

#nullable disable

namespace ScheduledMeets.Database.Migrations
{
    [DbContext(typeof(AccessContext))]
    [Migration("20230627182709_MemberInsteadAttendee")]
    partial class MemberInsteadAttendee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseHiLo(modelBuilder, "EntityFrameworkHiLoSequence");

            modelBuilder.HasSequence("EntityFrameworkHiLoSequence")
                .IncrementsBy(10);

            modelBuilder.Entity("ScheduledMeets.Persistence.Model.Attendance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"));

                    b.Property<long>("MeetId")
                        .HasColumnType("bigint")
                        .HasColumnName("meet_id");

                    b.Property<long>("MemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("member_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_attendance");

                    b.HasAlternateKey("MemberId", "MeetId")
                        .HasName("ak_attendance_member_id_meet_id");

                    b.HasIndex("MeetId")
                        .HasDatabaseName("ix_attendance_meet_id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_attendance_member_id");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("ScheduledMeets.Persistence.Model.Meet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("from");

                    b.Property<long>("MeetsId")
                        .HasColumnType("bigint")
                        .HasColumnName("meets_id");

                    b.Property<DateTimeOffset>("To")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("to");

                    b.HasKey("Id")
                        .HasName("pk_meet");

                    b.HasIndex("MeetsId")
                        .HasDatabaseName("ix_meet_meets_id");

                    b.ToTable("meet", (string)null);
                });

            modelBuilder.Entity("ScheduledMeets.Persistence.Model.Meets", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_meets");

                    b.ToTable("meets", (string)null);
                });

            modelBuilder.Entity("ScheduledMeets.Persistence.Model.Member", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"));

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<long>("MeetsId")
                        .HasColumnType("bigint")
                        .HasColumnName("meets_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_member");

                    b.HasIndex("MeetsId")
                        .HasDatabaseName("ix_member_meets_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_member_user_id");

                    b.ToTable("member", (string)null);
                });

            modelBuilder.Entity("ScheduledMeets.Persistence.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_user_username");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("ScheduledMeets.Persistence.Model.Attendance", b =>
                {
                    b.HasOne("ScheduledMeets.Persistence.Model.Meet", "Meet")
                        .WithMany("Attendances")
                        .HasForeignKey("MeetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_meet_meet_id");

                    b.HasOne("ScheduledMeets.Persistence.Model.Member", "Member")
                        .WithMany("Attendances")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_member_member_id");

                    b.Navigation("Meet");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ScheduledMeets.Persistence.Model.Meet", b =>
                {
                    b.HasOne("ScheduledMeets.Persistence.Model.Meets", "Meets")
                        .WithMany("ContainedMeets")
                        .HasForeignKey("MeetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meet_meets_meets_id");

                    b.Navigation("Meets");
                });

            modelBuilder.Entity("ScheduledMeets.Persistence.Model.Member", b =>
                {
                    b.HasOne("ScheduledMeets.Persistence.Model.Meets", "Meets")
                        .WithMany("Members")
                        .HasForeignKey("MeetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_meets_meets_id");

                    b.HasOne("ScheduledMeets.Persistence.Model.User", "User")
                        .WithMany("Attendees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_user_user_id");

                    b.Navigation("Meets");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScheduledMeets.Persistence.Model.Meet", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("ScheduledMeets.Persistence.Model.Meets", b =>
                {
                    b.Navigation("ContainedMeets");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("ScheduledMeets.Persistence.Model.Member", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("ScheduledMeets.Persistence.Model.User", b =>
                {
                    b.Navigation("Attendees");
                });
#pragma warning restore 612, 618
        }
    }
}
